services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - laravel_network

    web:
        image: nginx:latest
        container_name: laravel_web
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www
            - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network
        environment:
            - NGINX_CONFIG_PATH=${NGINX_CONFIG_PATH}

    db:
        image: mysql:8.0
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
