services:
    web:
        image: app-name:latest
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8089:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
